const MODELS: Record<string, string[]> = {
 ford : [
    "500",
    "Aerostar",
    "Aspire",
    "Bronco (Full Size)",
    "Bronco II",
    "C-Max",
    "Contour",
    "Crown Vic",
    "Ecosport",
    "Edge",
    "Escape",
    "Escort",
    "Excursion",
    "Expedition",
    "Explorer",
    "Festiva",
    "Fiesta",
    "Five Hundred",
    "Flex",
    "Focus",
    "Focus RS",
    "Freestar",
    "Freestyle",
    "Fusion",
    "GT",
    "Mustang",
    "Probe",
    "Ranger",
    "Taurus",
    "Taurus X",
    "Tempo",
    "Thunderbird",
    "Transit 150",
    "Transit 250",
    "Transit 350",
    "Transit Connect",
    "Truck-F150",
    "Truck-F150 Raptor",
    "Truck-F250 not Super Duty",
    "Truck-F250 Super Duty",
    "Truck-F350 not Super Duty",
    "Truck-F350 Super Duty",
    "Truck-F450 not Super Duty",
    "Truck-F450 Super Duty",
    "Truck-F550 Super Duty",
    "Truck-Ranger",
    "Van E150",
    "Van E250",
    "Van E350",
    "Van E450 Super Duty",
    "Van E550 Super Duty",
    "Windstar"
  ],
  Acura: ["ILX", "MDX", "RDX", "TLX"],
  Audi: ["A3", "A4", "Q5", "Q7"],
  BMW: ["3 Series", "5 Series", "X3", "X5"],
  Buick: ["Enclave", "Encore", "LaCrosse", "Regal"],
  Cadillac: ["ATS", "CT5", "Escalade", "XT5"],
  
}